/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["watchEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updatePassword"];
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLangs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminSettings"];
        trace?: never;
    };
    "/api/admin/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminUsers"];
        put?: never;
        post: operations["createAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAdminUser"];
        options?: never;
        head?: never;
        patch: operations["updateAdminUser"];
        trace?: never;
    };
    "/api/admin/users/{name}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetAdminUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminGroups"];
        put?: never;
        post: operations["createAdminGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAdminGroup"];
        options?: never;
        head?: never;
        patch: operations["updateAdminGroup"];
        trace?: never;
    };
    "/api/admin/languages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAdminLang"];
        options?: never;
        head?: never;
        patch: operations["updateAdminLang"];
        trace?: never;
    };
    "/api/admin/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminLangs"];
        put?: never;
        post: operations["createAdminLang"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/judgers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAdminJudger"];
        options?: never;
        head?: never;
        patch: operations["updateAdminJudger"];
        trace?: never;
    };
    "/api/admin/judgers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminJudgers"];
        put?: never;
        post: operations["createAdminJudger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/backups/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBackupSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateBackupSettings"];
        trace?: never;
    };
    "/api/admin/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBackups"];
        put?: never;
        post: operations["createBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/backups/{name}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/backups/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteBackup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["home"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/notice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateNotice"];
        trace?: never;
    };
    "/api/users/{id}/{year}/{month}/{day}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["userMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProblems"];
        put?: never;
        post: operations["createProblem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problem-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProblemState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProblem"];
        put?: never;
        post?: never;
        delete: operations["deleteProblem"];
        options?: never;
        head?: never;
        patch: operations["updateProblem"];
        trace?: never;
    };
    "/api/problems/{id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProblemVisibility"];
        trace?: never;
    };
    "/api/problems/{id}/rejudge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejudgeProblem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProblemAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/assets/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadProblemImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/assets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["problemPublicAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/data/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["problemPrivateData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/judge/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["problemPrivateJudge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/assets/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadProblemAsset"];
        delete: operations["deleteProblemAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/assets/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProblemAssetContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProblemAssetContent"];
        trace?: never;
    };
    "/api/problems/{id}/assets/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createProblemCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}/assets/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fillJudgeTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{id}.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadProblemAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssignments"];
        put?: never;
        post: operations["createAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssignment"];
        put?: never;
        post?: never;
        delete: operations["deleteAssignment"];
        options?: never;
        head?: never;
        patch: operations["updateAssignment"];
        trace?: never;
    };
    "/api/contests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listContests"];
        put?: never;
        post: operations["createContest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContest"];
        put?: never;
        post?: never;
        delete: operations["deleteContest"];
        options?: never;
        head?: never;
        patch: operations["updateContest"];
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSubmissions"];
        put?: never;
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSubmission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSubmission"];
        trace?: never;
    };
    "/api/submissions/{id}/rejudge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejudgeSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRank"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discussion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDiscussions"];
        put?: never;
        post: operations["createDiscussion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discussion/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDiscussion"];
        put?: never;
        post?: never;
        delete: operations["deleteDiscussion"];
        options?: never;
        head?: never;
        patch: operations["updateDiscussion"];
        trace?: never;
    };
    "/api/discussion/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discussion/{id}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
        };
        Site: {
            siteName: string;
            allowRegistration: boolean;
            allowGuestAccess: boolean;
            defaultSubmissionPublic: boolean;
        };
        HeatCell: {
            date: string;
            count: number;
        };
        Item: {
            id: number;
            title: string;
        };
        CreatedID: {
            id: number;
        };
        CountResult: {
            count: number;
        };
        Me: {
            id: number;
            name: string;
            /** Format: email */
            mail: string;
            bio: string;
            avatar: string;
            admin: boolean;
        };
        MeUpdate: {
            mail?: string;
            bio?: string;
            avatar?: string;
        };
        LoginRequest: {
            name: string;
            password: string;
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            mail: string;
            password: string;
        };
        Lang: {
            id: string;
            name: string;
            source: string;
        };
        UploadResult: {
            url: string;
        };
        PasswordUpdate: {
            oldPassword: string;
            newPassword: string;
        };
        AdminMembers: {
            users: components["schemas"]["AdminUser"][];
            groups: components["schemas"]["AdminGroup"][];
        };
        AdminSettings: {
            siteName: string;
            allowRegistration: boolean;
            allowGuestAccess: boolean;
            defaultSubmissionPublic: boolean;
            notice: string;
        };
        AdminSettingsPatch: {
            siteName?: string;
            allowRegistration?: boolean;
            allowGuestAccess?: boolean;
            defaultSubmissionPublic?: boolean;
            notice?: string;
        };
        BackupSettings: {
            enabled: boolean;
            /** @example 0 3 * * * */
            cron: string;
            keep: number;
        };
        BackupList: {
            running?: components["schemas"]["BackupRunning"];
            items: components["schemas"]["BackupItem"][];
        };
        BackupRunning: {
            name: string;
            /** Format: date-time */
            startedAt: string;
            stale: boolean;
        };
        BackupItem: {
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            size: number;
        };
        AdminUser: {
            id: number;
            name: string;
            /** Format: email */
            mail: string;
            role: string;
            groups: number[];
        };
        AdminUserPage: {
            items: components["schemas"]["AdminUser"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        AdminUserUpdate: {
            role: string;
            groups: number[];
        };
        AdminUserCreate: {
            name: string;
            /** Format: email */
            mail: string;
            password: string;
            role: string;
            groups: number[];
        };
        PasswordReset: {
            password: string;
        };
        AdminGroup: {
            id: number;
            name: string;
            users: number[];
        };
        AdminGroupPage: {
            items: components["schemas"]["AdminGroup"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        AdminGroupUpdate: {
            name: string;
            users: number[];
        };
        AdminLang: {
            id: string;
            name: string;
            source: string;
            image: string;
            compile: string;
            run: string;
        };
        AdminLangUpdate: {
            id: string;
            name: string;
            source: string;
            image: string;
            compile: string;
            run: string;
        };
        AdminLangCreate: components["schemas"]["AdminLangUpdate"];
        AdminJudger: {
            id: number;
            name: string;
            token?: string;
            online: boolean;
            /** Format: date-time */
            connectedAt: string | null;
            /** Format: date-time */
            activeAt: string | null;
            uptimeSeconds: number;
        };
        AdminJudgeQueue: {
            queued: number;
            running: number;
            done: number;
        };
        AdminJudgers: {
            judgers: components["schemas"]["AdminJudger"][];
            queue: components["schemas"]["AdminJudgeQueue"];
        };
        AdminJudgerUpdate: {
            name: string;
            auth?: string;
        };
        AdminJudgerCreate: {
            name: string;
        };
        ProblemListItem: {
            id: number;
            sort?: string;
            title: string;
            tags: string[];
            visible: boolean;
            mode: string;
            timeMs: number;
            memoryMb: number;
        };
        ProblemListPage: {
            items: components["schemas"]["ProblemListItem"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        Problem: {
            id: number;
            sort?: string;
            title: string;
            statement?: string;
            tags: string[];
            visible: boolean;
            mode: string;
            timeMs: number;
            memoryMb: number;
            cases: number;
            /** Format: int64 */
            dataBytes: number;
        };
        ProblemState: {
            problemId: number;
            ac: number;
            submit: number;
            discussions?: number;
            /** @enum {string} */
            status: "none" | "tried" | "ac" | "pending";
            submission?: components["schemas"]["ProblemRecord"];
        };
        ProblemRecord: {
            id: number;
            status: string;
            score: number;
            /** Format: date-time */
            createdAt: string;
        };
        ProblemCreate: {
            title: string;
            tags: string[];
            visible: boolean;
            mode: string;
            timeMs: number;
            memoryMb: number;
        };
        ProblemUpdate: {
            title?: string;
            statement?: string;
            tags?: string[];
            visible?: boolean;
            mode?: string;
            timeMs?: number;
            memoryMb?: number;
        };
        ProblemVisibilityUpdate: {
            visible: boolean;
        };
        AssetFile: {
            key: string;
            name: string;
            /** Format: int64 */
            size: number;
            editable: boolean;
        };
        ProblemAssets: {
            data: components["schemas"]["AssetFile"][];
            judge: components["schemas"]["AssetFile"][];
            assets: components["schemas"]["AssetFile"][];
            cases: number;
            /** Format: int64 */
            dataBytes: number;
        };
        AssetCaseCreate: {
            name: string;
            input: string;
            output: string;
        };
        AssetContent: {
            key: string;
            name: string;
            content: string;
        };
        AssetContentUpdate: {
            key: string;
            content: string;
        };
        Home: {
            notice: string;
            heatmap: components["schemas"]["HeatCell"][];
            problems: components["schemas"]["HomeProblem"][];
            assignments: components["schemas"]["HomeAssignment"][];
            contests: components["schemas"]["HomeContest"][];
        };
        HomeProblem: {
            id: number;
            title: string;
        };
        HomeAssignment: {
            id: number;
            title: string;
            status: string;
            total: number;
            done: number;
        };
        HomeContest: {
            id: number;
            title: string;
            status: string;
        };
        NoticeUpdate: {
            content: string;
        };
        Assignment: {
            id: number;
            title: string;
            /** Format: date-time */
            endAt: string;
            status: string;
            total: number;
            done: number;
            users: number[];
            groups: number[];
        };
        AssignmentListItem: {
            id: number;
            title: string;
            /** Format: date-time */
            endAt: string;
            status: string;
            total: number;
            done: number;
        };
        AssignmentListPage: {
            items: components["schemas"]["AssignmentListItem"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        AssignmentDetail: {
            assignment: components["schemas"]["Assignment"];
            problems: components["schemas"]["ProblemListItem"][];
            progress: components["schemas"]["AssignmentProgress"][];
        };
        AssignmentProgress: {
            user: string;
            ac: number;
            submit: number;
            problems: components["schemas"]["AssignmentProblemProgress"][];
        };
        AssignmentProblemProgress: {
            problemId: number;
            /** @enum {string} */
            status: "none" | "tried" | "ac" | "pending";
            score?: number;
        };
        AssignmentCreate: {
            title: string;
            /** Format: date-time */
            endAt: string;
            problems: components["schemas"]["ProblemRef"][];
            users: number[];
            groups: number[];
        };
        AssignmentUpdate: {
            title: string;
            /** Format: date-time */
            endAt: string;
            problems: components["schemas"]["ProblemRef"][];
            users: number[];
            groups: number[];
        };
        Contest: {
            id: number;
            title: string;
            kind: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            /** Format: date-time */
            freezeAt: string | null;
            status: string;
            total: number;
        };
        ContestListPage: {
            items: components["schemas"]["Contest"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        ContestDetail: {
            contest: components["schemas"]["Contest"];
            problems: components["schemas"]["ProblemListItem"][];
            rank: components["schemas"]["RankUser"][];
        };
        ContestCreate: {
            title: string;
            kind: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            freezeAt: string;
            problems: components["schemas"]["ProblemRef"][];
        };
        ContestUpdate: {
            title: string;
            kind: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            freezeAt: string;
            problems: components["schemas"]["ProblemRef"][];
        };
        ProblemRef: {
            id: number;
            sort: string;
        };
        Submission: {
            id: number;
            problemId: number;
            problemTitle: string;
            user: string;
            language: string;
            status: string;
            score: number;
            message: string;
            timeMs?: number;
            memoryKb?: number;
            public: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        SubmissionListItem: {
            id: number;
            problemId: number;
            problemTitle: string;
            user: string;
            language: string;
            status: string;
            timeMs?: number;
            memoryKb?: number;
            /** Format: date-time */
            createdAt: string;
        };
        SubmissionListPage: {
            items: components["schemas"]["SubmissionListItem"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        SubmissionDetail: {
            submission: components["schemas"]["Submission"];
            code: string;
            cases: components["schemas"]["Case"][];
            progress?: components["schemas"]["SubmissionProgress"];
        };
        SubmissionProgress: {
            /** @enum {string} */
            stage: "leased" | "download" | "prepare" | "compile" | "judge" | "upload";
            /** Format: int64 */
            done: number;
            /** Format: int64 */
            total?: number;
            /** Format: date-time */
            updatedAt: string;
        };
        SubmitRequest: {
            problemId: number;
            language: string;
            code: string;
            public: boolean;
        };
        SubmissionUpdate: {
            public: boolean;
        };
        Case: {
            no: number;
            status: string;
            timeMs?: number;
            memoryKb?: number;
            message: string;
        };
        RankProblem: {
            problemId: number;
            /** @enum {string} */
            status: "none" | "tried" | "ac" | "pending";
            submit: number;
            score: number;
            penalty: number;
        };
        RankUser: {
            rank: number;
            user: string;
            bio: string;
            avatar: string;
            ac: number;
            submit: number;
            score: number;
            penalty: number;
            problems: components["schemas"]["RankProblem"][];
        };
        RankUserPage: {
            items: components["schemas"]["RankUser"][];
            page: number;
            pageSize: number;
            total: number;
        };
        UserProfile: {
            user: components["schemas"]["PublicUser"];
            heatmap: components["schemas"]["HeatCell"][];
            solved: components["schemas"]["SolvedProblemPage"];
            activities: components["schemas"]["UserActivity"][];
        };
        SolvedProblemPage: {
            items: components["schemas"]["SolvedProblem"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        SolvedProblem: {
            id: number;
            title: string;
            tags: string[];
        };
        UserActivity: {
            /** @enum {string} */
            type: "submission" | "discussion";
            id: number;
            title: string;
            status?: string;
            problemId?: number;
            problemTitle?: string;
            /** Format: date-time */
            createdAt: string;
        };
        PublicUser: {
            name: string;
            bio: string;
            avatar: string;
            admin: boolean;
            ac: number;
            submit: number;
        };
        UserOption: {
            id: number;
            name: string;
        };
        Discussion: {
            id: number;
            title: string;
            author: string;
            tags: string[];
            pinned: boolean;
            locked: boolean;
            replies: number;
            /** Format: date-time */
            createdAt: string;
        };
        DiscussionListPage: {
            items: components["schemas"]["Discussion"][];
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        DiscussionCreate: {
            title: string;
            content: string;
            tags: string[];
        };
        DiscussionUpdate: {
            title?: string;
            content?: string;
            tags?: string[];
            pinned?: boolean;
            locked?: boolean;
        };
        DiscussionDetail: {
            discussion: components["schemas"]["Discussion"];
            content: string;
            comments: components["schemas"]["Comment"][];
        };
        Comment: {
            id: number;
            author: string;
            content: string;
            deleted: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CommentCreate: {
            content: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server dependencies are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Server dependencies are not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    watchEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events for lightweight live updates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public site settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdate"];
            };
        };
        responses: {
            /** @description Updated current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    updatePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdate"];
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered user */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLangs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submit languages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lang"][];
                };
            };
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded image */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
        };
    };
    getAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettings"];
                };
            };
        };
    };
    updateAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSettingsPatch"];
            };
        };
        responses: {
            /** @description Updated admin settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettings"];
                };
            };
        };
    };
    getAdminMembers: {
        parameters: {
            query?: {
                q?: string;
                users?: string;
                groups?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin member options */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMembers"];
                };
            };
        };
    };
    getAdminUsers: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
        };
    };
    createAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserCreate"];
            };
        };
        responses: {
            /** @description Created user */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMembers"];
                };
            };
        };
    };
    deleteAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMembers"];
                };
            };
        };
    };
    updateAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdate"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMembers"];
                };
            };
        };
    };
    resetAdminUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset user password */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordReset"];
                };
            };
        };
    };
    getAdminGroups: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGroupPage"];
                };
            };
        };
    };
    createAdminGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminGroupUpdate"];
            };
        };
        responses: {
            /** @description Created group */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMembers"];
                };
            };
        };
    };
    deleteAdminGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMembers"];
                };
            };
        };
    };
    updateAdminGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminGroupUpdate"];
            };
        };
        responses: {
            /** @description Updated group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMembers"];
                };
            };
        };
    };
    deleteAdminLang: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted language */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLang"][];
                };
            };
        };
    };
    updateAdminLang: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLangUpdate"];
            };
        };
        responses: {
            /** @description Updated language */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLang"][];
                };
            };
        };
    };
    getAdminLangs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin languages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLang"][];
                };
            };
        };
    };
    createAdminLang: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLangCreate"];
            };
        };
        responses: {
            /** @description Created language */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLang"][];
                };
            };
        };
    };
    deleteAdminJudger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted judger */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJudgers"];
                };
            };
        };
    };
    updateAdminJudger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminJudgerUpdate"];
            };
        };
        responses: {
            /** @description Updated judger */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJudgers"];
                };
            };
        };
    };
    getAdminJudgers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin judgers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJudgers"];
                };
            };
        };
    };
    createAdminJudger: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminJudgerCreate"];
            };
        };
        responses: {
            /** @description Created judger */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJudgers"];
                };
            };
        };
    };
    getBackupSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupSettings"];
                };
            };
        };
    };
    updateBackupSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackupSettings"];
            };
        };
        responses: {
            /** @description Updated backup settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupSettings"];
                };
            };
        };
    };
    getBackups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupList"];
                };
            };
        };
    };
    createBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created backup */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupItem"];
                };
            };
        };
    };
    downloadBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/gzip": string;
                };
            };
        };
    };
    deleteBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted backup */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    home: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Home data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Home"];
                };
            };
        };
    };
    updateNotice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticeUpdate"];
            };
        };
        responses: {
            /** @description Updated notice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Home"];
                };
            };
        };
    };
    userMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                year: string;
                month: string;
                day: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User uploaded media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    listProblems: {
        parameters: {
            query?: {
                q?: string;
                tag?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemListPage"];
                };
            };
        };
    };
    createProblem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemCreate"];
            };
        };
        responses: {
            /** @description Problem created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: {
                kind?: "problem" | "discussion";
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getProblemState: {
        parameters: {
            query?: {
                ids?: string;
                assignment?: number;
                contest?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem state for current user and page context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemState"][];
                };
            };
        };
    };
    getProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemUpdate"];
            };
        };
        responses: {
            /** @description Problem updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProblemVisibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemVisibilityUpdate"];
            };
        };
        responses: {
            /** @description Problem visibility updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemListItem"];
                };
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejudgeProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem submissions requeued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountResult"];
                };
            };
            /** @description Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProblemAssets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem assets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemAssets"];
                };
            };
        };
    };
    uploadProblemImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Problem image uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
        };
    };
    problemPublicAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public problem asset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    problemPrivateData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private problem data file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    problemPrivateJudge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private problem judge file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    uploadProblemAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @enum {string} */
                    section: "data" | "judge" | "assets";
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Problem asset uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemAssets"];
                };
            };
        };
    };
    deleteProblemAsset: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem asset deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemAssets"];
                };
            };
        };
    };
    getProblemAssetContent: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Text asset content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetContent"];
                };
            };
        };
    };
    updateProblemAssetContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetContentUpdate"];
            };
        };
        responses: {
            /** @description Text asset updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemAssets"];
                };
            };
        };
    };
    createProblemCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCaseCreate"];
            };
        };
        responses: {
            /** @description Problem case created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemAssets"];
                };
            };
        };
    };
    fillJudgeTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Judge template written */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemAssets"];
                };
            };
        };
    };
    downloadProblemAssets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem assets zip */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
        };
    };
    listAssignments: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentListPage"];
                };
            };
        };
    };
    createAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreate"];
            };
        };
        responses: {
            /** @description Assignment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
        };
    };
    getAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentDetail"];
                };
            };
            /** @description Assignment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentUpdate"];
            };
        };
        responses: {
            /** @description Assignment updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
            /** @description Assignment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listContests: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contest list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestListPage"];
                };
            };
        };
    };
    createContest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestCreate"];
            };
        };
        responses: {
            /** @description Contest created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
        };
    };
    getContest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contest detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestDetail"];
                };
            };
            /** @description Contest not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteContest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contest deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateContest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestUpdate"];
            };
        };
        responses: {
            /** @description Contest updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
            /** @description Contest not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSubmissions: {
        parameters: {
            query?: {
                problem?: string;
                user?: string;
                assignment?: string;
                contest?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionListPage"];
                };
            };
        };
    };
    createSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Submission created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
        };
    };
    getSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            /** @description Submission not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionUpdate"];
            };
        };
        responses: {
            /** @description Submission updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
            /** @description Owner or admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Submission not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejudgeSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission requeued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
            /** @description Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Submission not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRank: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rank list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankUserPage"];
                };
            };
        };
    };
    searchUsers: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOption"][];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: {
                solvedPage?: number;
                solvedPageSize?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDiscussions: {
        parameters: {
            query?: {
                q?: string;
                tags?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discussion list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussionListPage"];
                };
            };
        };
    };
    createDiscussion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscussionCreate"];
            };
        };
        responses: {
            /** @description Discussion created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
        };
    };
    getDiscussion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discussion detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussionDetail"];
                };
            };
            /** @description Discussion not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDiscussion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discussion deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDiscussion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscussionUpdate"];
            };
        };
        responses: {
            /** @description Discussion updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedID"];
                };
            };
            /** @description Discussion not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreate"];
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
