extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - '@vue/eslint-config-typescript'
  - '@vue/eslint-config-prettier/skip-formatting'
parserOptions:
  ecmaVersion: latest
rules:
  '@typescript-eslint/no-unused-vars': off
