version: '3'

services:
  doj:
    container_name: doj
    image: doveccl/doj
    pull_policy: always
    network_mode: host
    restart: unless-stopped
    privileged: true
    command: --server --judger
    volumes:
      - ./config.yaml:/doj/config.yaml
