version: '3'

volumes:
  data:

services:
  db:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/data/db
  doj:
    container_name: doj
    image: doveccl/doj
    pull_policy: always
    restart: unless-stopped
    network_mode: host
    privileged: true
    command: --server --judger
    depends_on:
      - db
    # volumes:
    #   - ./config.yaml:/doj/config.yaml
