CREATE TYPE "public"."contest_type" AS ENUM('OI', 'ICPC');--> statement-breakpoint
CREATE TYPE "public"."judge_status" AS ENUM('WAITING', 'JUDGING', 'AC', 'WA', 'PE', 'TLE', 'MLE', 'OLE', 'RE', 'CE', 'SE', 'FROZEN');--> statement-breakpoint
CREATE TYPE "public"."task_status" AS ENUM('WAITING', 'RUNNING', 'DONE', 'FAILED', 'CANCELLED');--> statement-breakpoint
CREATE TABLE "ai_coaching_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_coaching_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"submission_id" integer NOT NULL,
	"model" varchar(128) NOT NULL,
	"prompt_version" varchar(64) NOT NULL,
	"response_markdown" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assignment_groups" (
	"assignment_id" integer NOT NULL,
	"group_id" integer NOT NULL,
	CONSTRAINT "assignment_groups_assignment_id_group_id_pk" PRIMARY KEY("assignment_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "assignment_problems" (
	"assignment_id" integer NOT NULL,
	"problem_id" integer NOT NULL,
	"score" integer DEFAULT 100 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "assignment_problems_assignment_id_problem_id_pk" PRIMARY KEY("assignment_id","problem_id")
);
--> statement-breakpoint
CREATE TABLE "assignments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(160) NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"start_at" timestamp with time zone,
	"due_at" timestamp with time zone,
	"allow_late" boolean DEFAULT false NOT NULL,
	"ai_coaching_enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contest_problems" (
	"contest_id" integer NOT NULL,
	"problem_id" integer NOT NULL,
	"key" varchar(32) NOT NULL,
	"score" integer DEFAULT 100 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "contest_problems_contest_id_problem_id_pk" PRIMARY KEY("contest_id","problem_id")
);
--> statement-breakpoint
CREATE TABLE "contests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"legacy_id" varchar(64),
	"title" varchar(160) NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"type" "contest_type" DEFAULT 'OI' NOT NULL,
	"start_at" timestamp with time zone NOT NULL,
	"end_at" timestamp with time zone NOT NULL,
	"freeze_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "discussion_replies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discussion_replies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"topic_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"content_markdown" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "discussion_topics" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discussion_topics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"title" varchar(160) NOT NULL,
	"tags" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"linked_problem_id" integer,
	"linked_contest_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "files" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"legacy_id" varchar(64),
	"bucket" varchar(128) NOT NULL,
	"object_key" text NOT NULL,
	"filename" text NOT NULL,
	"content_type" varchar(255) NOT NULL,
	"size_bytes" bigint NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar(64) NOT NULL,
	"name" varchar(128) NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"builtin" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "judge_agents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "judge_agents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar(64) NOT NULL,
	"name" varchar(128) NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"token_hash" text NOT NULL,
	"labels" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"concurrency" integer DEFAULT 2 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"last_seen_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "judge_languages" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"name" varchar(128) NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"source_file" varchar(128) NOT NULL,
	"dockerfile" text NOT NULL,
	"command" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "judge_tasks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "judge_tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"submission_id" integer NOT NULL,
	"status" "task_status" DEFAULT 'WAITING' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"max_attempts" integer DEFAULT 3 NOT NULL,
	"locked_by" varchar(128),
	"locked_until" timestamp with time zone,
	"last_error" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "problem_files" (
	"problem_id" integer NOT NULL,
	"path" varchar(255) NOT NULL,
	"file_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "problem_files_problem_id_path_pk" PRIMARY KEY("problem_id","path")
);
--> statement-breakpoint
CREATE TABLE "problems" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "problems_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1000 CACHE 1),
	"legacy_id" varchar(64),
	"title" varchar(160) NOT NULL,
	"statement_markdown" text DEFAULT '' NOT NULL,
	"time_limit_ms" integer DEFAULT 1000 NOT NULL,
	"memory_limit_bytes" bigint DEFAULT 268435456 NOT NULL,
	"case_count" integer DEFAULT 0 NOT NULL,
	"test_cases" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tags" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"visible" boolean DEFAULT true NOT NULL,
	"solved_count" integer DEFAULT 0 NOT NULL,
	"submission_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "solved_problems" (
	"user_id" integer NOT NULL,
	"problem_id" integer NOT NULL,
	"first_submission_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "solved_problems_user_id_problem_id_pk" PRIMARY KEY("user_id","problem_id")
);
--> statement-breakpoint
CREATE TABLE "submission_cases" (
	"submission_id" integer NOT NULL,
	"case_index" integer NOT NULL,
	"status" "judge_status" NOT NULL,
	"time_ms" integer DEFAULT 0 NOT NULL,
	"memory_bytes" bigint DEFAULT 0 NOT NULL,
	"score" integer DEFAULT 0 NOT NULL,
	"message" text DEFAULT '' NOT NULL,
	CONSTRAINT "submission_cases_submission_id_case_index_pk" PRIMARY KEY("submission_id","case_index")
);
--> statement-breakpoint
CREATE TABLE "submissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"legacy_id" varchar(64),
	"user_id" integer NOT NULL,
	"problem_id" integer NOT NULL,
	"contest_id" integer,
	"assignment_id" integer,
	"language_id" varchar(64) NOT NULL,
	"source_code" text NOT NULL,
	"open" boolean DEFAULT false NOT NULL,
	"status" "judge_status" DEFAULT 'WAITING' NOT NULL,
	"time_ms" integer DEFAULT 0 NOT NULL,
	"memory_bytes" bigint DEFAULT 0 NOT NULL,
	"score" integer DEFAULT 0 NOT NULL,
	"message" text DEFAULT '' NOT NULL,
	"judge_progress" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "system_settings" (
	"key" varchar(128) PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_groups" (
	"user_id" integer NOT NULL,
	"group_id" integer NOT NULL,
	"manager" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_groups_user_id_group_id_pk" PRIMARY KEY("user_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"legacy_id" varchar(64),
	"name" varchar(32) NOT NULL,
	"email" varchar(255) NOT NULL,
	"password_hash" text NOT NULL,
	"introduction" varchar(500) DEFAULT '' NOT NULL,
	"solved_count" integer DEFAULT 0 NOT NULL,
	"submission_count" integer DEFAULT 0 NOT NULL,
	"disabled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "assignment_groups" ADD CONSTRAINT "assignment_groups_assignment_id_assignments_id_fk" FOREIGN KEY ("assignment_id") REFERENCES "public"."assignments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignment_groups" ADD CONSTRAINT "assignment_groups_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignment_problems" ADD CONSTRAINT "assignment_problems_assignment_id_assignments_id_fk" FOREIGN KEY ("assignment_id") REFERENCES "public"."assignments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignment_problems" ADD CONSTRAINT "assignment_problems_problem_id_problems_id_fk" FOREIGN KEY ("problem_id") REFERENCES "public"."problems"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contest_problems" ADD CONSTRAINT "contest_problems_contest_id_contests_id_fk" FOREIGN KEY ("contest_id") REFERENCES "public"."contests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contest_problems" ADD CONSTRAINT "contest_problems_problem_id_problems_id_fk" FOREIGN KEY ("problem_id") REFERENCES "public"."problems"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discussion_replies" ADD CONSTRAINT "discussion_replies_topic_id_discussion_topics_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."discussion_topics"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "problem_files" ADD CONSTRAINT "problem_files_problem_id_problems_id_fk" FOREIGN KEY ("problem_id") REFERENCES "public"."problems"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "problem_files" ADD CONSTRAINT "problem_files_file_id_files_id_fk" FOREIGN KEY ("file_id") REFERENCES "public"."files"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_groups" ADD CONSTRAINT "user_groups_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_groups" ADD CONSTRAINT "user_groups_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ai_coaching_submission_idx" ON "ai_coaching_sessions" USING btree ("submission_id","created_at");--> statement-breakpoint
CREATE INDEX "assignments_created_idx" ON "assignments" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "contest_problems_key_uidx" ON "contest_problems" USING btree ("contest_id","key");--> statement-breakpoint
CREATE INDEX "contests_start_idx" ON "contests" USING btree ("start_at");--> statement-breakpoint
CREATE INDEX "discussion_replies_topic_idx" ON "discussion_replies" USING btree ("topic_id","created_at");--> statement-breakpoint
CREATE INDEX "discussion_topics_tags_idx" ON "discussion_topics" USING btree ("tags");--> statement-breakpoint
CREATE INDEX "discussion_topics_updated_idx" ON "discussion_topics" USING btree ("updated_at");--> statement-breakpoint
CREATE UNIQUE INDEX "files_object_uidx" ON "files" USING btree ("bucket","object_key");--> statement-breakpoint
CREATE UNIQUE INDEX "groups_key_uidx" ON "groups" USING btree ("key");--> statement-breakpoint
CREATE UNIQUE INDEX "judge_agents_key_uidx" ON "judge_agents" USING btree ("key");--> statement-breakpoint
CREATE INDEX "judge_agents_enabled_idx" ON "judge_agents" USING btree ("enabled","sort_order");--> statement-breakpoint
CREATE INDEX "judge_agents_last_seen_idx" ON "judge_agents" USING btree ("last_seen_at");--> statement-breakpoint
CREATE INDEX "judge_languages_enabled_idx" ON "judge_languages" USING btree ("enabled","sort_order");--> statement-breakpoint
CREATE INDEX "judge_tasks_ready_idx" ON "judge_tasks" USING btree ("status","priority","created_at");--> statement-breakpoint
CREATE INDEX "judge_tasks_lease_idx" ON "judge_tasks" USING btree ("locked_until");--> statement-breakpoint
CREATE INDEX "problems_visible_idx" ON "problems" USING btree ("visible");--> statement-breakpoint
CREATE INDEX "problems_created_idx" ON "problems" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "solved_problems_problem_idx" ON "solved_problems" USING btree ("problem_id");--> statement-breakpoint
CREATE INDEX "submissions_user_idx" ON "submissions" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "submissions_problem_idx" ON "submissions" USING btree ("problem_id","created_at");--> statement-breakpoint
CREATE INDEX "submissions_contest_idx" ON "submissions" USING btree ("contest_id","created_at");--> statement-breakpoint
CREATE INDEX "submissions_assignment_idx" ON "submissions" USING btree ("assignment_id","created_at");--> statement-breakpoint
CREATE INDEX "submissions_status_idx" ON "submissions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "submissions_created_idx" ON "submissions" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "user_groups_group_idx" ON "user_groups" USING btree ("group_id");--> statement-breakpoint
CREATE UNIQUE INDEX "users_name_uidx" ON "users" USING btree (lower("name"));--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_uidx" ON "users" USING btree (lower("email"));--> statement-breakpoint
CREATE INDEX "users_rank_idx" ON "users" USING btree ("solved_count","submission_count");--> statement-breakpoint
CREATE INDEX "users_created_idx" ON "users" USING btree ("created_at");
