CREATE TABLE "judge_runners" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "judge_runners_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar(64) NOT NULL,
	"name" varchar(128) NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"kind" varchar(32) DEFAULT 'docker' NOT NULL,
	"endpoint" text,
	"auth_header" text,
	"concurrency" integer DEFAULT 2 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "judge_runners_key_uidx" ON "judge_runners" USING btree ("key");--> statement-breakpoint
CREATE INDEX "judge_runners_enabled_idx" ON "judge_runners" USING btree ("enabled","sort_order");